language: php
php:
- 5.4
- 5.5
- 5.6
- hhvm
before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-source --dev
script:
- phpunit -c app --coverage-text --coverage-clover=coverage.clover
- bin/behat
after_script:
- php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
addons:
  hosts:
    - zenium-backend.dev
