language: php
php:
- 5.4
- 5.5
- 5.6
before_script:
# PHP settings
- echo 'date.timezone = "Europe/Bucharest"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- echo 'always_populate_raw_post_data = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
# Travis + Composer
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-source --dev
# install Apache
- sudo apt-get update > /dev/null
- sudo apt-get install apache2 libapache2-mod-fastcgi
# enable php-fpm
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
- sudo a2enmod rewrite actions fastcgi alias
- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
# configure apache virtual hosts
- sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/zenium.conf
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/zenium.conf
- echo "127.0.0.1 zenium-backend.dev" | sudo tee -a /etc/hosts
- sudo a2ensite zenium.conf
# restart everything
- sudo service apache2 restart
script:
- phpunit -c app --coverage-text --coverage-clover=coverage.clover
- bin/behat
after_script:
- php bin/ocular code-coverage:upload --format=php-clover coverage.clover
