services:
    zenium.api.entity.service.abstract:
        class: Zenium\ApiBundle\Service\AbstractBaseService
        arguments: [@doctrine.orm.entity_manager, @zenium.api.exception_processing.service, @validator]

    zenium.api.question_category.service:
        class: Zenium\ApiBundle\Service\QuestionCategoryService
        parent: zenium.api.entity.service.abstract

    zenium.api.question.service:
        class: Zenium\ApiBundle\Service\QuestionService
        parent: zenium.api.entity.service.abstract

    zenium.api.exception.listener:
        class: Zenium\ApiBundle\Listener\ExceptionListener
        tags:
            - { name: kernel.event_subscriber }

    zenium.api.exception_processing.service:
        class: Zenium\ApiBundle\Service\ExceptionProcessingService
