services:
    api.entity.service.abstract:
        class: ApiBundle\Service\AbstractBaseService

    api.question_category.service:
        class: ApiBundle\Service\QuestionCategoryService
        parent: api.entity.service.abstract
